### ISSUE TITLE
Post about Lairig Ghru

### ISSUE THREAD

**Issue by samuelbalogh** [c0derabbit/11#19]
Lairig Ghru

"Off again, gorgeous day" wrote the barking mad [Maurice Wilson](https://en.wikipedia.org/wiki/Maurice_Wilson) in his diary in 1934 before he set off from his tent somewhere near the North Col on Mount Everest. This was his last entry in his notebook, and an expedition the following year found his body in his tent, died of starvation or exhaustion.

Being a total nutcase, he deeply believed that the worlds problems could be solved by fasting and faith in God. But he seems to have been a courageous, adventurous and, in a way, an inspiring fellow. He wanted to do a solo flight to Mount Everest, crash-land the plane on a slope of the mountain, and be the first man to ever climb it. 
The fact that he didn't know how to fly a plane, and that he didn't have any mountaineering experience whatsoever did not bother him the least bit. 

Unlike Maurice Wilson, we are aware of our limits, so our goal was much more modest. 

We wanted to hike the vast plateau in the hearth of the Cairngorms, a rocky tundra that towers above a massive valley, Lairig Ghru. Extremely exposed to bad weather and traversing fields of boulders, the terrain is very arduous to walk on.

We were prepared for the worst and planned our route carefully, including a series of designated waypoints with respective turn-back times. We packed our stuff and off we went.
We could hardly believe how lucky we got: the weather, although misty, was extremely benign. The path was physically very demanding, but there was no difficulty in navigation and our clothes remained fairly dry.  
Up on the plateau, the summits raised above the clouds. It felt magical to see such a harsh place wrapped in a peaceful blanket of white fluff. We were also glad to see some snow: the snow patches in the vast corries of the area are known to be the ones which persist for the [longest time anywhere in the UK](https://en.wikipedia.org/wiki/Snow_patches_in_Scotland), oftentimes from one winter to the next.

We summited Braeriach (1296), Cairn Toul (1291) and Sgor an Lochain Uaine (1258) - the third, fourth and fifth highest points in the UK, respectively. 

The peak called Devil's Point was a smaller challenge by comparison - but the name is worth mentioning. The Gaelic name, Bod an Deamhain, apparently means the Penis of the Demon, but when Queen Victoria visited the area, the local guide, to avoid embarrassment, used this euphemistic name for the peak - so it stuck.

After descending into the valley, we had a peaceful night in our tent and rose to a gorgeous sunny day - off we went for miles and miles through the Lairig Ghru, back to Aviemore, where we had started.

**Comment by c0derabbit** [comment]
done :)
